# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67e542285700b892e024b7bcbeb483d780403eca3a0c6751a98aaef191eb62f152b9f418748ef47facfec1537776075be958a4f2fbde0304786bba35e73b6d6b

test:
  secret_key_base: 9ee98d20d67a64c52f07c8285c67ca0c8f0c7f951974d34d41b8cd84051b2789f5badc78d1b3f279d262b9a5501c917a290a7d7120b33aaffea79580f08db2dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
